### ISSUE TITLE
Unexpected token import on new project

### ISSUE THREAD

**Issue by bradyisom** [thymikee/jest-preset-angular#4]
Following the instructions in the README with a brand new Angular CLI 1.0 generated project results in an "Unexpected token import" error when running jest.

Environment:
OS: OSX Sierra
@angular/cli: v1.0.0
node: v7.5.0
Typescript: v2.2.2

Reproduction steps:
```
$ ng new temp-jest
$ npm install --save-dev jest jest-preset-angular @types/jest
$ npm uninstall --save-dev @types/jasmine
```

Follow the instructions in the README to create `setupJest.ts` and `jestGlobalMocks.ts` as well as the instructions to add the `package.json` settings and scripts.

Running the following command:
```
$ npm test
```

results in the following error:
```
 FAIL  src/app/app.component.spec.ts
  ● Test suite failed to run

    /Users/bradyisom/Development/temp/temp-jest/src/setupJest.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){require('ts-jest').install();import 'jest-preset-angu
lar';
                                                                                                                          ^^^^^^
    SyntaxError: Unexpected token import

      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at process._tickCallback (internal/process/next_tick.js:103:7)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.005s
Ran all test suites.
error Command failed with exit code 1.
```

Also, running with `--no-cache` option results in the same error.

**Comment by thymikee** [comment]
Ok, so I can repro this! The problem is `"module"` entry in `src/tsconfig.app.json`. Looks like `ts-jest` needs it to be set to `"commonjs"` instead of `"es2015"`:
```json
"compilerOptions": {
  "module": "commonjs"
}
```

From the preset side, it should use `src/tsconfig.spec.json` by default, I'll address a PR in a minute.
After changing anything in TS config, jest need to be run with `--no-cache` once.

**Comment by thymikee** [comment]
Just published 0.0.8, can you see if it works for you?

**Comment by bradyisom** [comment]
That is working now. Thank you. Now I'll try upgrading my much bigger project. :pray:

**Comment by thymikee** [comment]
Awesome! Let me know if you have any troubles.

**Comment by srod** [comment]
Hello, I ran into the same error message with third party packages:

```javascript
 FAIL  src/app/shared/components/toggle/toggle.component.spec.ts
  ● Test suite failed to run

    /Users/rodolphe/Dropbox/www/ekino/oav-pegase/node_modules/ng-dynamic/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './src/dynamic-html/index';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token export
      
      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at Object.<anonymous> (src/app/shared/components/toggle/toggle.component.spec.ts:6:20)
```
And the same for import:
```javascript
 FAIL  src/app/simulator/simulator-simulation-tab-1.component.spec.ts
  ● Test suite failed to run

    /Users/rodolphe/Dropbox/www/ekino/oav-pegase/node_modules/angular2-ui-switch/dist/index.js:7
    import { NgModule } from '@angular/core';
    ^^^^^^
    SyntaxError: Unexpected token import
      
      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
      at Object.<anonymous> (src/app/simulator/simulator-simulation-tab-1.component.spec.ts:7:28)
```
I'm not totally sure that's the same issue, let me know if you prefer a new one.

**Comment by thymikee** [comment]
You need to add that package to the whitelist of `transformIgnorePatterns`. Include something like this in Jest config entry in your `package.json`:
```js
"transformIgnorePatterns": [
  "node_modules/(?!@ngrx|angular2-ui-switch)"
]
```

**Comment by srod** [comment]
Still the same, here my jest config in package.json:

```
  "jest": {
    "preset": "jest-preset-angular",
    "setupTestFrameworkScriptFile": "<rootDir>/src/setupJest.ts",
    "transformIgnorePatterns": [
      "node_modules/(?!@ngrx|angular2-ui-switch|ng-dynamic)"
    ]
  }
```

**Comment by thymikee** [comment]
Oh, you also need to run jest with `--no-cache`, e.g. `npm test -- --no-cache`

**Comment by srod** [comment]
Yes, already did, no effects, got the same errors.

**Comment by thymikee** [comment]
Could you provide a minimal repro on GitHub, so I could see what can be done?

**Comment by srod** [comment]
Sure, I will do that tomorrow, thanks.

**Comment by srod** [comment]
I've created the minimal repro: https://github.com/srod/minimal-repro-jest-preset-angular
```
git clone git@github.com:srod/minimal-repro-jest-preset-angular.git
```
```
yarn
```
```
yarn test
```

**Comment by thymikee** [comment]
Ok, so you'll need to add `"allowJs": true` to `"compilerOptions"` in you `src/tsconfig.spec.json` file.

**Comment by srod** [comment]
It's working, thank you !

**Comment by rantiev** [comment]
One issue after another:
1) first i had the same unable to import 'jest-preset-angular', ok fixed by updating ts config (i can't see why i need ts config, if i don't have any ts files in my project, jest use it inside? any possibility to get rid of this?)

2) then it started to shout i have no zone.js module 
ok installed it manually

3) after this it shouting "Cannot find module '@angular/core/testing' from 'setupJest.js'"
I afraid what will be next...

**Comment by thymikee** [comment]
@rantiev Are you sure you're trying this on Angular 2+? Because as far as I know having zone.js is mandatory, and using typescript is de facto standard in Angular development. 
You can see example app generated from Angular CLI in example directory of this repo

**Comment by rantiev** [comment]
That actually was my quesion, reading this article i wasn't able to understand for which version of angular this thing is supposed to work (https://www.xfive.co/blog/testing-angular-faster-jest/)

I'm trying to get it work with angular 1.6.x.

**Comment by Chowarmaan** [comment]
When working with Ionic3 framework, you need to add the @ionic-native into the transformIgnorePatterns in the package.json.

 "transformIgnorePatterns": [
      "node_modules/(?!@ngrx|angular2-ui-switch|@ionic-native)"
    ]

**Comment by kidd3** [comment]
I'm having the same issue as described above, where my jest test is returning:
`SyntaxError: Unexpected token import`

I'm importing a package of my own creation, and i've tried adding it to the whitelist:

    "transformIgnorePatterns": [
        "node_modules/(?!@ngrx|service-layer)"
    ]

And my tsconfig.spec.json file is as follows:

    {
    "extends": "./tsconfig.es5.json",
    "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "module": "commonjs",
    "target": "es6",
    "baseUrl": "",
    "types": [
    "jest",
    "node"
    ],
    "allowJs": true
    },
    "files": [
    "**/*.spec.ts"
    ]
    }

Any help would be apprciated

**Comment by jkyoutsey** [comment]
This appears to be an issue in Angular 7.2.0.
I fail just trying to load up setupJest.ts.

```
    Details:

    /Users/jyoutsey/src/MyMedstudy/ng/src/setupJest.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import 'jest-preset-angular';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import
```
I'm running the following versions of Jest:
```
    "@types/jest": "^23.3.12",
    "jest": "^23.6.0",
    "jest-preset-angular": "^6.0.2",
```
Jest config in package.json:
```
  "jest": {
    "preset": "jest-preset-angular",
    "setupTestFrameworkScriptFile": "<rootDir>/src/setupJest.ts"
  },
```

**Comment by ahnpnl** [comment]
Hi @jkyputsey,

The issue you have is because jest asks for module:common.js in your tsconfig.spec.json. Once you declare that and run jest --clearCache then rerun your tests, it will be fine.
