### ISSUE TITLE
"require(...).install is not a function" with Jest 23

### ISSUE THREAD

**Issue by PatrickLehnerXI** [thymikee/jest-preset-angular#171]
When adding Jest 23, ts-jest 23 and jest-preset-angular 5.2.3 to an Angular 6 app, running tests results in the execution error "`TypeError: require(...).install is not a function`" for each test file.
The same works with Jest 22, ts-jest 22 and jest-preset-angular 5.2.3.

## Reproduction Steps
* create a new Angular 6 app with Angular-CLI 6: `ng new test-app`
* `cd test-app`
* follow jest-preset-angular installation steps from [the README](https://github.com/thymikee/jest-preset-angular/blob/bc6c523c7b891a7d7143626e34970a8223f99a83/README.md) or [the blog post](https://www.xfive.co/blog/testing-angular-faster-jest/)
  * `npm install -D jest ts-jest jest-preset-angular`
  * add file `src/setupJest.ts` with contents [1]  
  * add file `src/jestGlobalMocks.ts` with contents [2]
  * add the configuration key to `package.json` [3]
* run jest: `npx jest`

**Expected result:**
* `src/app/app.component.spec.ts` is executed and have 2 passes and 1 failure (like with `npm run test`)

**Actual result:**
* `src/app/app.component.spec.ts` fails to start with the following error:
```
 FAIL  src/app/app.component.spec.ts
  ● Test suite failed to run

    TypeError: require(...).install is not a function

    > 1 | import 'jest-preset-angular';
        |                                                            ^
      2 | import './jestGlobalMocks'; // browser mocks globally available for every test
      3 |

      at Object.<anonymous> (src/setupJest.ts:1:60)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.746s
Ran all test suites.
```

## Additional Notes

Everything works as expected when installing `jest@22`, `ts-jest@22` and `jest-preset-angular@5.2.2` instead.

## Reproduction Repo

https://github.com/PatrickLehnerXI/jest-preset-angular-repro-issue171

---

[1] `src/setupJest.ts`:
```
import 'jest-preset-angular';
import './jestGlobalMocks'; // browser mocks globally available for every test
```

[2] `src/jestGlobalMocks.ts`:
```
const mock = () => {
  let storage = {};
  return {
    getItem: key => key in storage ? storage[key] : null,
    setItem: (key, value) => storage[key] = value || '',
    removeItem: key => delete storage[key],
    clear: () => storage = {},
  };
};

Object.defineProperty(window, 'localStorage', {value: mock()});
Object.defineProperty(window, 'sessionStorage', {value: mock()});
Object.defineProperty(window, 'getComputedStyle', {
  value: () => ['-webkit-appearance']
});
```

[3] configuration key in `package.json`:
```
{
  "jest": {
    "preset": "jest-preset-angular",
    "setupTestFrameworkScriptFile": "<rootDir>/src/setupJest.ts"
  }
}
```

**Comment by thymikee** [comment]
Have you tried the "next" tag? That's one thing. The second is I recall this issue, can you search better on this issue tracker or Google? I'm on a mobile right now, so it's a hard task with Github UI :D

**Comment by PatrickLehnerXI** [comment]
@thymikee unfortunately, with `jest-preset-angular@next` (and `jest@latest`, `ts-jest@latest`), I now get the following error:

```
 FAIL  src/app/app.component.spec.ts
  ● Test suite failed to run

    Some errors occurred while attempting to read from <containing path>\jest-preset-angular-repro-issue171\src\tsconfig.spec.json: error TS5058: The specified path does not exist: '<containing path>/tsconfig.json'.


      Error: Some errors occurred while attempting to read from <containing path>\jest-preset-angular-repro-issue171\src\tsconfig.spec.json: error TS5058: The specified path does not exist: '<containing path>/tsconfig.json'.
      at readCompilerOptions (node_modules/jest-preset-angular/node_modules/ts-jest/src/utils.ts:42:11)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.136s
Ran all test suites.
```

Note that the relative reference to `../tsconfig.json` that Angular has by default in `src/tsconfig.spec.json` is **incorrectly resolved** to `./../tsconfig.json` instead of `./src/../tsconfig.json`.

@ahnpnl thanks for the hint, but unfortunately, I can't see anything actionable in that ts-jest issue, nor the linked issue in the jest repo. The original poster of kulshekhar/ts-jest#603 finally said that their problem went away but changing the version of one of their other dependencies.

TBH this really doesn't speak to the "Zero configuration testing platform" that Jest advertises :(

(Unfortunately, since this is for a work project, and we were going to try if Jest is viable for testing Angular apps, I can't spend too much more time on this.)

**Comment by ahnpnl** [comment]
@PatrickLehnerXI I think your issue is related to [this issue](https://github.com/kulshekhar/ts-jest/issues/625)

**Comment by ahnpnl** [comment]
hi @PatrickLehnerXI , would you please try to verify if the issue still exists with v6.0.0 just release ?

**Comment by herkulano** [comment]
@ahnpnl I have the same error but only started to have it after upgrading to v6

**Comment by ahnpnl** [comment]
hi @herkulano , would you please try to clean `jest` cache and rerun your tests ? I had this error but it was gone after I cleaned `jest` cache

**Comment by herkulano** [comment]
@ahnpnl works! thank you!

**Comment by AnthonyNahas** [comment]
@ahnpnl that worked for me too 👍

**Comment by thearchitgarg** [comment]
`jest --clearCache` solved the issue for me too. Thanks.
