### ISSUE TITLE
[Bug]: Cannot find module '@angular/localize/init' from 'jest-config/setup.ts'

### ISSUE THREAD

**Issue by PriyankaNGowda** [thymikee/jest-preset-angular#1861]
### Version

26.6.1

### Steps to reproduce

After upgrading angular version to 14,when running unit testcases(npm run test) getting error like below

Cannot find module '@angular/localize/init' from 'jest-config/setup.ts'.

We upgraded jest version and jest-preset-angular version and all but its not picking.

### Expected behavior

All unit testcases should pass after running npm run test.

### Actual behavior

All unit testcases are failing after running npm run test.

### Environment

```shell
our version:
"jest":26.6.1
"@types/jest":27.4.1,
"jest-preset-angular": "^8.4.0",
"ts-jest": "^26.4.3"
```

**Comment by ahnpnl** [comment]
We don’t support jest 26 anymore. Would you please upgrade to jest 28 and use 12.2.3?

If you still have the issue, please try to reproduce with our example apps https://github.com/thymikee/jest-preset-angular/tree/main/examples

without a repo, it’s not possible to help
