### PR TITLE
Fix: File separator issue on Windows causing error: jest: got error running globalsetup cannot find module @angular\compiler-cli

### LINKED ISSUE #2073: [Bug]: File separator issue on Windows causing `error: jest: got error running globalsetup cannot find module @angular\compiler-cli`
### Version

13.1.0

### Steps to reproduce

- Create an app on Windows, minimal example: https://github.com/pal03377/minimal-jest-pathsep-issue
- Run `npm run test`
- Observe this error message
```
error: jest: got error running globalsetup
cannot find module @angular\compiler-cli 
```

### Expected behavior

The tests should run properly

### Actual behavior

The error appears

### Additional context

This breaks since #2063.

It is related to wrong handling of file path separators.

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    jest: ^29.5.0 => 29.5.0
```

### PR DESCRIPTION
**Pull request by pal03377**
## Summary

This fixes #2073

## Test plan

- `git clone https://github.com/pal03377/jest-preset-angular` somewhere else
- `cd jest-preset-angular` from there
- `npm install`, then `npm run build`
- `npm link` to locally link this repo
- `cd path/to/minimal-example` from here https://github.com/pal03377/minimal-jest-pathsep-issue
- `npm install`, then `npm link jest-preset-angular`
- `npm run test` to verify that it now works

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by ahnpnl — APPROVED** [review]
thanks!
