### ISSUE TITLE
Cannot find module 'zone.js/dist/zone.js' after upgrade to zone.js 0.11.0 

### ISSUE THREAD

**Issue by splincode** [thymikee/jest-preset-angular#445]
## 🐛 Bug Report

```text
 FAIL  file-size.pipe.spec.ts
  ● Test suite failed to run

    Cannot find module 'zone.js/dist/zone.js' from '../../../../../node_modules/jest-preset-angular/build/setupJest.js'

    Require stack:
      /node_modules/jest-preset-angular/build/setupJest.js
      /node_modules/jest-preset-angular/index.js
      src/stubs/setupJest.ts

      at Resolver.resolveModule (../../../../../node_modules/jest-resolve/build/index.js:307:11)
```

## To Reproduce

- upgrade zone.js 0.11.0

## envinfo

```
System:
    OS: MacOS

Npm packages:
    jest: last
    jest-preset-angular: last
    typescript: last
```

**Comment by ahnpnl** [comment]
Related to https://github.com/angular/angular/pull/38473#issuecomment-675865330

**Comment by ocombe** [comment]
there is still an issue after upgrading to 0.11.1: `Cannot find module 'zone.js/dist/zone.js' from 'node_modules/jest-preset-angular/build/setupJest.js'`

It should load `zone.js/dist/zone`, not `zone.js/dist/zone.js`, because they have changed the build setup.

**Comment by ahnpnl** [comment]
Thanks @ocombe ! 

There should be a PR to update the usage of  `zone.js` too, which was mentioned in https://github.com/angular/angular/pull/38473#issuecomment-674404753 .

cc @JiaLiPassion

**Comment by Benji1109** [comment]
I still got the problem what have mentioned @ocombe

**Comment by ahnpnl** [comment]
the workaround in the meanwhile is manually copy the content of `node_modules/jest-preset-angular/build/setupJest.js` and adjust all the import for `zone.js`

**Comment by JiaLiPassion** [comment]
Sorry for the inconveniences, now 0.11.1 is available, I will create a PR to update.

**Comment by splincode** [comment]
https://github.com/thymikee/jest-preset-angular/blob/master/src/setup-jest.ts#L5

@JiaLiPassion 

correct will be

```
require('zone.js/dist/zone');
```

**Comment by splincode** [comment]
Oh, I see, awesome PR

https://github.com/thymikee/jest-preset-angular/pull/448/files
