### ISSUE TITLE
regression in zone patch in 8.1.1 with it.each as tagged template literal

### ISSUE THREAD

**Issue by bgoscinski** [thymikee/jest-preset-angular#359]
The fix released in 8.1.1 didn't consider usage of it.each as tagged template literal and currently it breaks with 
```
 FAIL  src/app/app.component.spec.ts (12.248s)
  ● AppComponent › encountered a declaration exception

    TypeError: row.map is not a function

      113 |     foo  | bar
      114 |     ${1} | ${2}
    > 115 |   `('it.each should work with table as a tagged template literal', ({foo, bar}) => {
          |    ^
      116 |     expect(foo).toBe(1);
      117 |     expect(bar).toBe(2);
      118 |   });

      at node_modules/jest-preset-angular/build/zone-patch/index.js:137:73
          at Array.map (<anonymous>)
      at src/app/app.component.spec.ts:115:4
      at Object.<anonymous> (src/app/app.component.spec.ts:9:1)
```
This usage works in 8.1.0.  ~~I'll submit a PR with regression test in example app~~ it's here: #360

**Comment by ahnpnl** [comment]
cc @JiaLiPassion could you please take a look ?

**Comment by JiaLiPassion** [comment]
@ahnpnl , sure , will check it now.

**Comment by JiaLiPassion** [comment]
@ahnpnl , I created a refactor PR to simplify the logic and handle all the cases, it should work for all the known cases for now. And @bgoscinski  thank you for the test cases.
