### ISSUE TITLE
[Bug]: File separator issue on Windows causing `error: jest: got error running globalsetup cannot find module @angular\compiler-cli`

### ISSUE THREAD

**Issue by pal03377** [thymikee/jest-preset-angular#2073]
### Version

13.1.0

### Steps to reproduce

- Create an app on Windows, minimal example: https://github.com/pal03377/minimal-jest-pathsep-issue
- Run `npm run test`
- Observe this error message
```
error: jest: got error running globalsetup
cannot find module @angular\compiler-cli 
```

### Expected behavior

The tests should run properly

### Actual behavior

The error appears

### Additional context

This breaks since #2063.

It is related to wrong handling of file path separators.

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    jest: ^29.5.0 => 29.5.0
```

**Comment by ahnpnl** [comment]
Your `jest-preset-angular` version in lock file is still at **12.2.3** https://github.com/pal03377/minimal-jest-pathsep-issue/blob/1235622b978476778cb3631038212eaa85f0e70e/package-lock.json#L440

You are using `@angular-builder/jest` which they need to upgrade their version to have **13.1.0**

**Comment by ahnpnl** [comment]
ah ha, I saw the problem now https://github.com/thymikee/jest-preset-angular/actions/runs/4919099866/jobs/8786367135

**Comment by pal03377** [comment]
Thanks for looking into it @ahnpnl !

I'll try to create a version of the example where the version is correct everywhere later, but I'm pretty sure that the issue is there because I was able to fix the issue in our repository by modifying the build output from this repo accordingly. This obviously is no viable solution, so I opened #2079 to fix it here directly.

**Comment by pal03377** [comment]
I didn't manage to create a "clean" version, but my main `jest-preset-angular` package (directly in `node_modules/jest-preset-angular`) is updated and also seems to be the source of the issue:

```
Error: Jest: Got error running globalSetup - C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\global-setup.js, reason: Cannot find
 module '@angular\compiler-cli'
Require stack:
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\build\utils\ngcc-jest-processor.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\build\config\global-setup.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\global-setup.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-util\build\requireOrImportModule.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-util\build\index.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-config\build\getCacheDirectory.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-config\build\Defaults.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-config\build\normalize.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-config\build\index.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-cli\build\init\index.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-cli\build\run.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-cli\build\index.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest\build\index.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular-builders\jest\dist\index.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular-devkit\architect\node\index.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular\cli\src\command-builder\architect-base-command-module.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular\cli\src\command-builder\architect-command-module.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular\cli\src\commands\test\cli.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular\cli\src\commands\command-config.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular\cli\src\command-builder\command-runner.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular\cli\lib\cli\index.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular\cli\lib\init.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at findAngularCompilerCliVersion (C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\build\utils\ngcc-jest-processor.js:27:26)
    at runNgccJestProcessor (C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\build\utils\ngcc-jest-processor.js:61:38)
    at C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\build\config\global-setup.js:18:56
    at Generator.next (<anonymous>)
    at C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\build\config\global-setup.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\build\config\global-setup.js:4:12)
    at globalSetup (C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\build\config\global-setup.js:14:27)
```

When I downgrade `jest-preset-angular` to version 13.0.1 locally, the error disappears.

**Comment by pal03377** [comment]
I didn't manage to create a "clean" version, but my main `jest-preset-angular` package (directly in `node_modules/jest-preset-angular`) is updated and also seems to be the source of the issue:

```
Error: Jest: Got error running globalSetup - C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\global-setup.js, reason: Cannot find
 module '@angular\compiler-cli'
Require stack:
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\build\utils\ngcc-jest-processor.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\build\config\global-setup.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\global-setup.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-util\build\requireOrImportModule.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-util\build\index.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-config\build\getCacheDirectory.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-config\build\Defaults.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-config\build\normalize.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-config\build\index.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-cli\build\init\index.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-cli\build\run.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-cli\build\index.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest\build\index.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular-builders\jest\dist\index.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular-devkit\architect\node\index.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular\cli\src\command-builder\architect-base-command-module.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular\cli\src\command-builder\architect-command-module.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular\cli\src\commands\test\cli.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular\cli\src\commands\command-config.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular\cli\src\command-builder\command-runner.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular\cli\lib\cli\index.js
- C:\main\projects\minimal-jest-pathsep-issue\node_modules\@angular\cli\lib\init.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at findAngularCompilerCliVersion (C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\build\utils\ngcc-jest-processor.js:27:26)
    at runNgccJestProcessor (C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\build\utils\ngcc-jest-processor.js:61:38)
    at C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\build\config\global-setup.js:18:56
    at Generator.next (<anonymous>)
    at C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\build\config\global-setup.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\build\config\global-setup.js:4:12)
    at globalSetup (C:\main\projects\minimal-jest-pathsep-issue\node_modules\jest-preset-angular\build\config\global-setup.js:14:27)
```

When I downgrade `jest-preset-angular` to version 13.0.1 locally, the error disappears.
